Completed Serial.Write() Table
Lastrellik/Calico-Home-Security pull request #55
Opened 2017-03-27 00:06 UTC by Boomstick105

Creats a table for Serial.Write() commands

Notes;
For the Component.cpp I did this for now, if we need to figure out what out in the comment section, I'll work on this asap, but for now I got most of the working table up and running.

Checked it a couple times, hopefully this is in the correct format and typo free, if not I'll look into addressing what needs to be addressed.
  
//Need to figure out if we can put the component type created and the pin it's
  //set at with the Serial.write and the table, for now just doing base message
  //Logger::Log("Component " + componentType + " is set at pin " + pin);

2017-03-27 02:27 UTC, Lastrellik requested changes
Just a few changes here before we can merge it. Shouldn't take too long.

2017-03-27 02:27 UTC, Lastrellik commented on src/Alarm.cpp
> +    Serial.write(30004); // 30004 = Command, N/A, Execute Command: Calibrate
The 30004 command is the command I send from the PI to the Arduino when I want it to calibrate. This isn't the right 5 digit number.

2017-03-27 02:27 UTC, Lastrellik commented on src/Alarm.cpp
> +  Serial.write(30005); // 30005 = Command, N/A, Execute Command: Trigger
Again, 000 - 099 are for commands that the PI sends back to the arduino to tell it to do something.

2017-03-27 02:27 UTC, Lastrellik commented on src/Alarm.cpp
> +  Serial.write(30006); // 30006 = Commmand, N/A, Execute Commmand: Reset Calibration
Same as the above issues.

2017-03-27 02:27 UTC, Lastrellik commented on src/Alarm.cpp
> +  Serial.write(30002); // 30002 = Command, N/A, Execute Command: Disarm
Same as above issues

2017-03-27 02:27 UTC, Lastrellik commented on src/Alarm.cpp
> +  Serial.write(30003); // 30003 = Command, N/A, Execute Command: Silence
Same as above issues

2017-03-27 02:27 UTC, Lastrellik commented on src/Buzzer.cpp
> +  //if(Properties::DEBUGGING_ACTIVE) Serial.println("Buzzer has started sounding");
Yeah we can remove this code. That should be fine.

2017-03-27 02:27 UTC, Lastrellik commented on src/Buzzer.cpp
> +  //if(Properties::DEBUGGING_ACTIVE) Serial.println("Buzzer has stopped sounding");
We can remove this line of code too.

2017-03-27 02:27 UTC, Lastrellik commented on src/Laser.cpp
> +  Purpose: Manges the lASER and creats a LASER object
Few Typos here

2017-03-27 02:27 UTC, Lastrellik commented on src/Laser.cpp
>      digitalWrite(Component::getPin(), LOW);
We can remove it. I'm sure that's fine.

2017-03-27 02:27 UTC, Lastrellik commented on src/Laser.h
> +  Purpose: Manges the lASER and creats a LASER object
Manges? Manages? Another Typo :P

2017-03-27 02:30 UTC, Boomstick105 commented on src/Laser.h
> +  Purpose: Manges the lASER and creats a LASER object
I'll get right on fixing these issues, I guess I was miss understanding the command function a little bit, shouldn't be to hard to update these real quick.

2017-03-27 02:56 UTC, Boomstick105 commented on src/Laser.h
> +  Purpose: Manges the lASER and creats a LASER object
Should be all updated now by getting rid of the 30000's and the small typos

2017-03-27 03:09 UTC, Lastrellik requested changes
So The changes all look good with the exception of a few typos. I also never loaded the code onto the arduino because it's currently plugged into the PI on the other side of the room. I'll load it up and look at it tonight.

2017-03-27 03:09 UTC, Lastrellik commented on docs/development/logging.md
> +* [700 - 999] - Currently reserved for David Tille.
I like this.

2017-03-27 03:09 UTC, Lastrellik commented on src/Component.h
> +    Which are used to determine the type of compoent Ex. "LED" and where it is
Typo in compoent

2017-03-27 03:09 UTC, Lastrellik commented on src/Laser.cpp
> +  Turns the lASER on
Should all letters in LASER be upper case?

2017-03-27 16:03 UTC, Lastrellik commented
@Zeustopher can you load this code and make sure it functions? I think that removing the Laser::toggle() from the cpp but not from the header may cause it to break. I hate C++. My arduino is tied up with the PI at the moment.

2017-03-27 16:08 UTC, Boomstick105 commented
I forgot to remove that from the laser.h, I edit it a couple of times and then went back I can remove that from the resubmit real quick @Lastrellik

2017-03-27 18:28 UTC, Zeustopher commented
@Boomstick105 - There are several build errors when I try and build this branch in PlatformIO. Is it building on properly on your machine?

2017-03-27 18:37 UTC, Boomstick105 commented
I'm getting errors from the properties and logger class because of a / and
an extra bracket. Just pushed the fix and it built fine.

On Mar 27, 2017 12:28 PM, "Christopher Nash" <notifications@github.com>
wrote:

> @Boomstick105 <https://github.com/Boomstick105> - There are several build
> errors when I try and build this branch in PlatformIO. Is it building on
> properly on your machine?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Lastrellik/Calico-Home-Security/pull/55#issuecomment-289542327>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYRK_yu7Bxe0pvYss6Ez_mwuBiKWlwh8ks5rp__igaJpZM4Mpp0u>
> .
>

2017-03-28 13:12 UTC, Lastrellik commented
@Boomstick105 we should be able to remove the logger class. We're not building datapackets anymore, so there should be no problem with removing that one.

2017-03-28 14:45 UTC, Zeustopher approved these changes
I think there are some additional tweaks we can make to this as we move forward, but this Pull Request is starting to get large and already has quite a few commits to it. I vote that we merge it in as-is right now and work on those additional changes (like removing the Logger class) in another Pull Request.

If anyone else agrees go ahead and merge this pull request.

2017-03-28 14:49 UTC, Lastrellik commented
Merged [#55](https://github.com/Lastrellik/Calico-Home-Security/pull/55)

2017-03-28 14:49 UTC, merged